[package]
name = "dra"
version = "0.2.0"
edition = "2021"
authors = ["devmatteini <dev.matteini@gmail.com>"]
description = "A command line tool to download release assets from GitHub"
homepage = "https://github.com/devmatteini/dra"
repository = "https://github.com/devmatteini/dra"
documentation = "https://github.com/devmatteini/dra"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["github", "cli"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
ureq = { version = "2.3.1", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
structopt = "0.3.25"
dialoguer = "0.9.0"
indicatif = "0.16.2"

[dev-dependencies]
test-case = "1.2.1"
