name: Release

on:
  push:
    tags:
      # x.y.z version format
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the release version from the tag
        run: |
          echo "DRA_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Print release version
        run: |
          echo "Version is: $DRA_VERSION"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/create-github-release.sh "$DRA_VERSION"
  # NOTE: always set shell: bash, otherwise on Windows there might be problems!
  build:
    name: ${{ matrix.job.os }}
    needs: [ create-release ]
    runs-on: ${{ matrix.job.runner }}
    strategy:
      matrix:
        job:
          - os: linux
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: false
          - os: linux-armv6
            runner: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
            use-cross: true
          - os: linux-arm64
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use-cross: true
          - os: macos
            runner: macos-latest
            target: x86_64-apple-darwin
            use-cross: false
          - os: windows
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
    steps:
      - uses: actions/checkout@v3

      - name: Get the release version from the tag
        shell: bash
        run: |
          echo "DRA_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Install prerequisites
        shell: bash
        run: |
          case ${{ matrix.job.os }} in
            linux-armv6) sudo apt-get -y update ; sudo apt-get -y install gcc-arm-linux-gnueabihf ;;
            aarch64-unknown-linux-gnu) sudo apt-get -y update ; sudo apt-get -y install gcc-aarch64-linux-gnu ;;
          esac

      - name: Install minimal stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          profile: minimal
          override: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.job.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup build tools
        if: matrix.job.use-cross == true
        shell: bash
        run: |
          if ! command -v cross >/dev/null; then
            cargo install cross
          fi
          echo "CARGO_BIN=cross" >>$GITHUB_ENV

      - name: Export cargo target
        shell: bash
        run: echo "CARGO_TARGET=${{ matrix.job.target }}" >>$GITHUB_ENV

      - name: Build release binary
        shell: bash
        run: make release

      - name: Build archive
        id: build_archive
        shell: bash
        run: |
          asset=$(./scripts/create-release-archive.sh "$DRA_VERSION" "${{ matrix.job.os }}" "$CARGO_TARGET")
          echo "ARCHIVE=$asset" >> $GITHUB_OUTPUT

      - name: Upload assets
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/upload-github-release-assets.sh \
              "$DRA_VERSION" \
              ${{ steps.build_archive.outputs.ARCHIVE }}

      - name: Build and upload debian package
        if: matrix.job.os == 'linux'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo install cargo-deb
          deb_file=$(./scripts/create-deb.sh "$CARGO_TARGET")

          ./scripts/upload-github-release-assets.sh "$DRA_VERSION" "$deb_file"
